### PR TITLE
Change GRU activation function to work on GPU

### PR DESCRIPTION
**Pull request by mathslove**
changed activation func for gru to work on gpu
see why here:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU

### CODE REVIEW

**Comment by mathslove** [comment]
fix for issue #3

**Comment by mathslove** [comment]
Since GRU4Rec started training on the GPU, the time per epoch has dropped from 50 minutes to 4 for my dataset, and in some cases GRU4Rec wins over SASRec and BERT4Rec.

**Comment by asash** [comment]
Hi. thanks for submitting this. I'll look at this after the christmas/new year holidays and merge if it indeed improves GRU training.

**Comment by asash** [comment]
Hi, I evaluated the fix, and it indeed improves GRU performance. I am accepting the PR.

**Pull request merged**
